// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3cIrJ-ai68g6B9VdBeWbviHE19VJnth0',
    appId: '1:889871397832:web:59759f9259ab10063186fd',
    messagingSenderId: '889871397832',
    projectId: 'herenciapos',
    authDomain: 'herenciapos.firebaseapp.com',
    storageBucket: 'herenciapos.firebasestorage.app',
    measurementId: 'G-MXM64FMZY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoAL4_X3hRiojp-ZShFj5jBmXUCp0hk5k',
    appId: '1:889871397832:android:7517af198648fa183186fd',
    messagingSenderId: '889871397832',
    projectId: 'herenciapos',
    storageBucket: 'herenciapos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHHIXwuXuQdjDsss6KYIICC9oqT7dufO8',
    appId: '1:889871397832:ios:333c88fb00d406043186fd',
    messagingSenderId: '889871397832',
    projectId: 'herenciapos',
    storageBucket: 'herenciapos.firebasestorage.app',
    iosBundleId: 'com.example.finalPosHerencia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHHIXwuXuQdjDsss6KYIICC9oqT7dufO8',
    appId: '1:889871397832:ios:333c88fb00d406043186fd',
    messagingSenderId: '889871397832',
    projectId: 'herenciapos',
    storageBucket: 'herenciapos.firebasestorage.app',
    iosBundleId: 'com.example.finalPosHerencia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3cIrJ-ai68g6B9VdBeWbviHE19VJnth0',
    appId: '1:889871397832:web:2025276059118dd83186fd',
    messagingSenderId: '889871397832',
    projectId: 'herenciapos',
    authDomain: 'herenciapos.firebaseapp.com',
    storageBucket: 'herenciapos.firebasestorage.app',
    measurementId: 'G-DVHBBZG4MS',
  );
}
